parameters:
    env(ELASTICSEARCH_HOST): 'http://es01:9200'

api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            # - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Model'

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'

    elasticsearch:
        enabled: true
        hosts: ['%env(ELASTICSEARCH_HOST)%']